ENVELOPE_SCHEMA := schema/envelope.schema.json
ENVELOPE_RS     := bindings/rust/glassworks-envelope/src/generated.rs
ENVELOPE_PY_PKG := bindings/python/glassworks-envelope
ENVELOPE_PY     := $(ENVELOPE_PY_PKG)/src/glassworks_envelope/_generated.py

GENERATED := $(ENVELOPE_RS) $(ENVELOPE_PY)

banner_rs = "// @generated by \`make gen\` from $(1) — DO NOT EDIT.\n// Edit the schema and re-run \`make gen\`. CI fails if this file is stale.\n\n"
banner_py = "\# @generated by \`make gen\` from $(1) — DO NOT EDIT.\n\# Edit the schema and re-run \`make gen\`. CI fails if this file is stale.\n\#\n"

# $(call prepend,<banner>,<file>)
prepend = printf $(1) | cat - $(2) > $(2).tmp && mv $(2).tmp $(2)

.PHONY: gen gen-rust gen-python check-gen check-schema test test-rust test-python

gen: gen-rust gen-python

gen-rust:
	cargo typify --output $(ENVELOPE_RS) $(ENVELOPE_SCHEMA)
	# Every wire enum is #[non_exhaustive], so a new kind or command is a compatible
	# release. typify does not emit the attribute, so it is added here, and check-gen
	# fails if a regeneration ever drops it. Structs and struct-like variants are left
	# constructible: clients build commands with struct literals.
	perl -0pi -e 's/^([ \t]*)(pub enum )/$$1#[non_exhaustive]\n$$1$$2/mg' $(ENVELOPE_RS)
	$(call prepend,$(call banner_rs,$(ENVELOPE_SCHEMA)),$(ENVELOPE_RS))

## `--strict-types int` is not a style preference. Without it pydantic's lax mode
## coerces a numeric *string* into an integer, so `"mail_id": "4210"` validates in
## Python while the Rust binding — and the schema's own `type: integer` — reject
## it. The `mail-id-not-integer` fixture fails loudly if this flag is dropped.
## `bool` is strict for the same reason: lax mode reads `"yes"` or `"true"` as `True`,
## where Rust and the schema's `type: boolean` reject it. The
## `viewer-focus-not-boolean` fixture fails loudly if `bool` is dropped.
## Note that whole-model `strict=True` is NOT the same fix and is wrong here: it
## also refuses to read a plain string into a generated enum, which rejects most
## of the corpus.
gen-python:
	uv run --with 'datamodel-code-generator==0.71.0' datamodel-codegen \
	  --input $(ENVELOPE_SCHEMA) \
	  --input-file-type jsonschema \
	  --output $(ENVELOPE_PY) \
	  --output-model-type pydantic_v2.BaseModel \
	  --target-python-version 3.11 \
	  --disable-timestamp \
	  --strict-types int bool
	$(call prepend,$(call banner_py,$(ENVELOPE_SCHEMA)),$(ENVELOPE_PY))

## Fails if committed generated code does not match the schema.
check-gen: gen
	git diff --exit-code -- $(GENERATED)

## Schema-level checks — no language bindings involved.
## Keep rfc3339-validator. Without it, `format: date-time` is annotation-only and a
## malformed timestamp validates. The envelope has no date-time field today; the
## package is here so that the first one is actually checked.
check-schema:
	uv run --with jsonschema --with referencing --with rfc3339-validator \
	  python conformance/schema_is_valid.py
	uv run --with jsonschema --with referencing --with rfc3339-validator \
	  python conformance/validate_corpus.py

test: check-schema test-rust test-python

test-rust:
	cargo test --workspace

test-python:
	cd $(ENVELOPE_PY_PKG) && uv run --with pytest --with pydantic pytest -v
