# @generated by `make gen` from schema/envelope.schema.json — DO NOT EDIT.
# Edit the schema and re-run `make gen`. CI fails if this file is stale.
#
# generated by datamodel-codegen:
#   filename:  envelope.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel, StrictBool, conint, constr


class Attention(StrEnum):
    Normal = 'Normal'
    NeedsYou = 'NeedsYou'
    Urgent = 'Urgent'


class Data1(BaseModel):
    code: conint(ge=-2147483648, le=2147483647, strict=True) = Field(
        ..., description='The process exit code.'
    )


class EventKind4(BaseModel):
    kind: Literal['AgentExited']
    data: Data1 = Field(..., description='The agent process exited.')


class Data2(BaseModel):
    tool: str | None = Field(
        ..., description='The current tool, or null between tools.'
    )


class EventKind5(BaseModel):
    kind: Literal['AgentActivity']
    data: Data2 = Field(
        ...,
        description="The tool the agent is now running changed — the decoration behind a `working — <tool>` label. Content-free by contract: the tool's *name* is a safe category, its input never rides the bus. Separate from `AgentStatus` on purpose, because the status is asserted independently by another signal and folding the two together would let them fight over the label.",
    )


class Data8(BaseModel):
    name: str = Field(..., description="The workflow's template name.")


class EventKind12(BaseModel):
    kind: Literal['WorkflowStarted']
    data: Data8 = Field(..., description='A workflow run started.')


class Data9(BaseModel):
    phase: str
    attempt: conint(ge=0, le=4294967295, strict=True) = Field(
        ..., description='1-based attempt counter for this phase.'
    )


class EventKind13(BaseModel):
    kind: Literal['PhaseEntered']
    data: Data9 = Field(
        ..., description='The workflow entered a phase, possibly as a retry of it.'
    )


class Data10(BaseModel):
    verdict: str = Field(
        ...,
        description="The evaluator's verdict. An open vocabulary owned by the orchestration plane.",
    )
    gap: float | None = Field(
        ..., description='Optional numeric gap score behind the verdict.'
    )
    flags: list[str] = Field(
        ..., description='Content-free flag labels attached by the evaluator.'
    )


class EventKind14(BaseModel):
    kind: Literal['EvaluationVerdict']
    data: Data10 = Field(
        ...,
        description='A phase evaluation rendered its verdict — never the raw output it judged.',
    )


class Data11(BaseModel):
    deviation_kind: str = Field(
        ...,
        description='The deviation category. An open vocabulary owned by the orchestration plane.',
    )
    note: str = Field(..., description='A short, content-free note.')


class EventKind15(BaseModel):
    kind: Literal['DeviationLogged']
    data: Data11 = Field(
        ..., description='The run deviated from its plan in a logged, non-fatal way.'
    )


class Data12(BaseModel):
    legs: conint(ge=0, le=4294967295, strict=True) = Field(
        ..., description='How many legs launched.'
    )


class EventKind16(BaseModel):
    kind: Literal['FanOutStarted']
    data: Data12 = Field(
        ...,
        description="A parallel region fanned out. Leg events parent to this event's span, which is the concurrent-fan-out ambiguity the span tree exists to resolve.",
    )


class Data13(BaseModel):
    leg: conint(ge=0, le=4294967295, strict=True) = Field(
        ..., description="The leg's 0-based index within its region."
    )
    leg_id: str = Field(..., description="The leg's stable id.")
    outcome: str = Field(
        ...,
        description='The leg outcome. An open vocabulary owned by the orchestration plane.',
    )


class EventKind17(BaseModel):
    kind: Literal['LegCompleted']
    data: Data13 = Field(..., description='One leg of a parallel region finished.')


class EventKind18(BaseModel):
    kind: Literal['WorkflowCompleted']


class Data14(BaseModel):
    reason: str = Field(..., description='A short, content-free failure reason.')


class EventKind19(BaseModel):
    kind: Literal['WorkflowFailed']
    data: Data14 = Field(..., description='The workflow run failed terminally.')


class AgentStatus1(BaseModel):
    status: Literal['Fresh']


class AgentStatus2(BaseModel):
    status: Literal['Working']


class AgentStatus3(BaseModel):
    status: Literal['Idle']


class AgentStatus4(BaseModel):
    status: Literal['UnsentDraft']


class AgentStatus6(BaseModel):
    status: Literal['Unknown']


class AgentStatus7(BaseModel):
    status: Literal['Dead']


class AgentRole1(BaseModel):
    role: Literal['Solo']


class AgentRole2(BaseModel):
    role: Literal['Lead']


class SpawnOrigin1(BaseModel):
    origin: Literal['Operator']


class Data15(BaseModel):
    source: str = Field(..., description='A string identifying the external trigger.')


class SpawnOrigin3(BaseModel):
    origin: Literal['ExternalTrigger']
    data: Data15


class AgentView2(BaseModel):
    kind: Literal['Grid']
    data: dict[str, Any] = Field(
        ...,
        description="A `gridwire::GridDelta`, opaque to this schema: decode it with the `gridwire` crate's own `GridDelta` type. Its serde shape is gridwire's, verbatim; the envelope carries it without re-describing it, so the two cannot drift apart.",
    )


class AgentView3(BaseModel):
    kind: Literal['Event']
    data: dict[str, Any] | str = Field(
        ...,
        description='A `gridwire::BackendEvent`, opaque to this schema: decode it with the `gridwire` crate\'s own `BackendEvent` type. Its serde shape is gridwire\'s, verbatim; the envelope carries it without re-describing it, so the two cannot drift apart. A unit variant serializes as a bare string (`"Bell"`), the others as a one-key object (`{"Title": "..."}`).',
    )


class Color1(BaseModel):
    Indexed: conint(ge=0, le=255, strict=True) = Field(
        ...,
        description='A 256-colour palette index; 0 through 15 are the ANSI colours.',
    )


class RgbItem(RootModel[conint(ge=0, le=255, strict=True)]):
    root: conint(ge=0, le=255, strict=True)


class Color2(BaseModel):
    Rgb: list[RgbItem] = Field(
        ...,
        description='A 24-bit truecolour, as [r, g, b].',
        max_length=3,
        min_length=3,
    )


class Color(RootModel[Literal['Default'] | Color1 | Color2]):
    root: Literal['Default'] | Color1 | Color2 = Field(
        ...,
        description="A cell colour: the terminal default, a palette index, or a 24-bit truecolour. `Default` defers to the renderer's theme rather than naming a colour, which is what lets one grid render correctly under light and dark themes. DEPRECATED since 0.1.1 with `AgentView::Terminal`, its only user (through `Cell`); removed at the next breaking release. It carries no `deprecated` keyword itself: on a union the Python generator puts the flag on the model's own root field, which pydantic cannot then read, and the deprecation already reaches it through `Cell` and `ScreenSnapshot`.",
        title='Color',
    )


class StructuredTurn(BaseModel):
    role: str = Field(..., description='The conversational role of this turn.')
    summary: str = Field(
        ..., description='A short, content-free summary — never raw output.'
    )


class GateProducer(StrEnum):
    AgentPermission = 'AgentPermission'
    AgentQuestion = 'AgentQuestion'
    MemoryPromotion = 'MemoryPromotion'
    OrchestrationGate = 'OrchestrationGate'


class GateOption(BaseModel):
    id: str = Field(
        ...,
        description='Machine-stable identifier, echoed back in a `Select` resolution.',
    )
    label: str = Field(..., description='Human-readable text shown to the operator.')


class GateResolution1(BaseModel):
    kind: Literal['Select']
    option: str = Field(..., description="The chosen option's `id`.")
    note: str | None = Field(
        ..., description='Optional free-text note accompanying the selection.'
    )


class GateResolution2(BaseModel):
    kind: Literal['Answer']
    text: str = Field(..., description="The operator's free-text answer.")


class GateResolution3(BaseModel):
    kind: Literal['Chat']


class GateResolution(RootModel[GateResolution1 | GateResolution2 | GateResolution3]):
    root: GateResolution1 | GateResolution2 | GateResolution3 = Field(
        ...,
        description='How an operator resolved a gate. Three modes, always all three: a preset option, free text, or escalating to a live conversation. `Chat` resolves by the interaction itself rather than by a payload — for an agent gate the operator is dropped into the session, so there is nothing to carry.',
        title='GateResolution',
    )


class BusCommand2(BaseModel):
    kind: Literal['Snapshot']


class Target4(BaseModel):
    kind: Literal['Broadcast']


class Caps(BaseModel):
    status: StrictBool
    view: StrictBool


class KindClass(StrEnum):
    Agent = 'Agent'
    Memory = 'Memory'
    Curation = 'Curation'
    Orchestration = 'Orchestration'


class KindFilter(BaseModel):
    classes: list[KindClass] = Field(
        ...,
        description='The classes to subscribe to. An empty list means *all* classes, not none — the common case is an unfiltered subscription, and making that the empty value keeps a client from having to enumerate a list that grows.',
    )


class AgentRef(RootModel[str]):
    root: str = Field(
        ...,
        description="An agent's vendor-neutral id, and the join key every plane stamps.\n\nDeliberately unconstrained. The producer's own type is an unvalidated string, so any pattern here would be a schema that rejects ids the bus accepts — the same superset rule the registry schema states from the other direction, where a *key* pattern must stay a superset of every id the bus accepts.",
        title='AgentRef',
    )


class SessionId(RootModel[str]):
    root: str = Field(
        ...,
        description="The hosted session's own id, used to resume it. Distinct from `AgentRef`: one names the agent to every plane, the other is the vendor's handle for its conversation.",
        title='SessionId',
    )


class FactoryRef(RootModel[str]):
    root: str = Field(
        ...,
        description='Identifies an agent factory — a spawn template and the project scope around it.',
        title='FactoryRef',
    )


class GroupRef(RootModel[str]):
    root: str = Field(
        ..., description='Identifies an operator-named set of agents.', title='GroupRef'
    )


class WorkflowRef(RootModel[str]):
    root: str = Field(
        ..., description='Identifies a workflow run.', title='WorkflowRef'
    )


class MemoryItemRef(RootModel[str]):
    root: str = Field(
        ...,
        description="Identifies a memory item — an opaque ref into the owning plane's store, never the item itself.",
        title='MemoryItemRef',
    )


class GateId(RootModel[str]):
    root: str = Field(..., description='Identifies a gate.', title='GateId')


class EventId(RootModel[str]):
    root: str = Field(..., description='Identifies a bus event.', title='EventId')


class MailId(
    RootModel[conint(ge=-9223372036854775808, le=9223372036854775807, strict=True)]
):
    root: conint(ge=-9223372036854775808, le=9223372036854775807, strict=True) = Field(
        ...,
        description='Identifies a message in the durable mail store. An integer, unlike every other id here, because the mail store assigns it.',
        title='MailId',
    )


class TraceId(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: constr(pattern=r'^(?!0{32}$)[0-9a-f]{32}$') = Field(
        ...,
        description='A trace id: 32 lowercase hex characters, not all zero. Propagate it unchanged along a causal chain; mint one only where a chain truly begins.',
        title='TraceId',
    )


class SpanId(RootModel[str]):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    root: constr(pattern=r'^(?!0{16}$)[0-9a-f]{16}$') = Field(
        ...,
        description='A span id: 16 lowercase hex characters, not all zero.',
        title='SpanId',
    )


class TraceContext(BaseModel):
    trace_id: TraceId
    span_id: SpanId
    parent_span_id: SpanId | None = Field(
        None,
        description="The causing event's span. Absent at the root of a chain; omitted rather than null, so a root context is byte-identical to a context from a producer that does not parent its events.",
    )


class SubjectRef1(BaseModel):
    kind: Literal['Agent']
    id: AgentRef


class SubjectRef2(BaseModel):
    kind: Literal['Factory']
    id: FactoryRef


class SubjectRef3(BaseModel):
    kind: Literal['Workflow']
    id: WorkflowRef


class SubjectRef4(BaseModel):
    kind: Literal['Memory']
    id: MemoryItemRef


class SubjectRef5(BaseModel):
    kind: Literal['Gate']
    id: GateId


class SubjectRef(
    RootModel[SubjectRef1 | SubjectRef2 | SubjectRef3 | SubjectRef4 | SubjectRef5]
):
    root: SubjectRef1 | SubjectRef2 | SubjectRef3 | SubjectRef4 | SubjectRef5 = Field(
        ...,
        description='What an event is about — the single identity join key across planes. The same agent or factory id is stamped by every plane, so their timelines reconcile without a translation table.',
        title='SubjectRef',
    )


class Data3(BaseModel):
    gate_id: GateId
    resolution: GateResolution


class EventKind7(BaseModel):
    kind: Literal['GateAnswered']
    data: Data3 = Field(..., description='An operator resolved an open gate.')


class Data5(BaseModel):
    items: list[MemoryItemRef] = Field(
        ...,
        description="The injected item ids — opaque refs into the owning plane's store.",
    )
    scores: list[float] = Field(
        ...,
        description='Ranker scores, parallel-length to `items`. The parallel-length rule is enforced by the ingress that accepts these, not by this schema: JSON Schema cannot relate two array lengths, and a contract that silently fails to check a rule it appears to state is worse than one that does not state it.',
    )
    reason: str = Field(
        ...,
        description='Short, content-free reason — which ranker and cut produced this.',
    )


class EventKind9(BaseModel):
    kind: Literal['MemoryInjected']
    data: Data5 = Field(
        ...,
        description="The memory plane injected items into an agent's context. Content-free by construction: ids, scores, and a short reason — never the fact text or the query that retrieved it. The carrying event's subject names the agent the injection went to.",
    )


class Data6(BaseModel):
    gate_id: GateId
    content_hash: str = Field(
        ...,
        description="Content hash of the proposed fact — a content-free ref, in practice sha256 hex. Not pattern-constrained here: the producer's own field is a plain string, and a schema stricter than the producer would reject documents the bus accepts.",
    )
    proposed_scope: str = Field(
        ...,
        description='Proposed promotion scope. An open vocabulary owned by the memory plane; new values arrive without a schema change.',
    )
    source_trust: str = Field(
        ...,
        description='Provenance trust level. An open vocabulary owned by the memory plane.',
    )
    ts: str = Field(
        ...,
        description="Producer-side timestamp, as provenance. Distinct from the envelope's `at`, which is when the bus broadcast the frame. Not `format`-constrained, for the same superset reason as `content_hash`.",
    )


class EventKind10(BaseModel):
    kind: Literal['CurationProposed']
    data: Data6 = Field(
        ...,
        description="The memory plane's curator proposed a promotion and opened a curation gate. Content-free: hex refs and vocabulary strings, never fact text. The carrying event's subject is the gate.",
    )


class Data7(BaseModel):
    gate_id: GateId
    reason: str = Field(..., description='Free-text, content-free reason.')
    ts: str = Field(..., description='Producer-side timestamp, as provenance.')


class EventKind11(BaseModel):
    kind: Literal['GateVoided']
    data: Data7 = Field(
        ...,
        description="The owning plane voided a curation gate — for instance because the content drifted before it could be applied. A doorbell, not an authority: a consumer verifies against the owning plane's store before acting on it. Void is terminal and absorbing, so answered-then-voided is a legitimate sequence rather than a conflict.",
    )


class AgentStatus5(BaseModel):
    status: Literal['Blocked']
    gate_id: GateId


class AgentStatus(
    RootModel[
        AgentStatus1
        | AgentStatus2
        | AgentStatus3
        | AgentStatus4
        | AgentStatus5
        | AgentStatus6
        | AgentStatus7
    ]
):
    root: (
        AgentStatus1
        | AgentStatus2
        | AgentStatus3
        | AgentStatus4
        | AgentStatus5
        | AgentStatus6
        | AgentStatus7
    ) = Field(
        ...,
        description='The observable lifecycle state of an agent — exactly one at a time. `Fresh` is the spawn state, left only by the first real prompt, so a never-driven agent reads differently from one that finished a turn. `UnsentDraft` is the state that earns its own name: the operator typed a prompt and never submitted it, so nothing is running while it looks as though something is. `Unknown` means no signal, not an error.',
        title='AgentStatus',
    )


class AgentRole3(BaseModel):
    role: Literal['Teammate']
    parent: AgentRef


class AgentRole(RootModel[AgentRole1 | AgentRole2 | AgentRole3]):
    root: AgentRole1 | AgentRole2 | AgentRole3 = Field(
        ...,
        description="The agent's position in the agent tree. Only `Solo` is emitted today; `Lead` and `Teammate` are reserved so the tree work lands additively rather than as a wire change.",
        title='AgentRole',
    )


class SpawnOrigin2(BaseModel):
    origin: Literal['Agent']
    data: AgentRef


class SpawnOrigin(RootModel[SpawnOrigin1 | SpawnOrigin2 | SpawnOrigin3]):
    root: SpawnOrigin1 | SpawnOrigin2 | SpawnOrigin3 = Field(
        ...,
        description='Where a spawn request came from. Only `Operator` is emitted today; the rest are reserved.',
        title='SpawnOrigin',
    )


class AgentView4(BaseModel):
    kind: Literal['Transcript']
    data: StructuredTurn


class Cell(BaseModel):
    ch: str = Field(
        ...,
        description="Exactly one Unicode scalar value.\n\nDeliberately *not* length-constrained, and the reason is a cross-language trap worth stating: JSON Schema's `minLength`/`maxLength` count characters, but implementations disagree on what a character is — a validator over UTF-16 counts an astral scalar such as an emoji as two, while one over code points counts it as one. A `maxLength: 1` here would therefore accept the same document in one language and reject it in another, which is precisely the divergence this repository's corpus exists to prevent. The single-scalar rule is enforced by the producer's own character type instead.",
    )
    bold: StrictBool
    fg: Color
    bg: Color


class Gate(BaseModel):
    gate_id: GateId
    producer: GateProducer
    subject_ref: SubjectRef
    options: list[GateOption] = Field(
        ...,
        description='Ordered choices the operator may select. Empty for an open-answer gate — a client must therefore offer free text and escalation even when this list is empty, rather than rendering an empty button row.',
    )
    context_summary: str = Field(
        ...,
        description='A brief human-readable summary of why the human is needed — never raw content.',
    )


class Data16(BaseModel):
    kinds: KindFilter
    agents: list[AgentRef] | None = Field(
        ...,
        description='Restrict to events about these agents. Null means no agent filter — distinct from an empty list, which filters everything out.',
    )
    caps: Caps


class BusCommand1(BaseModel):
    kind: Literal['Subscribe']
    data: Data16 = Field(
        ...,
        description='Subscribe to events, with an optional agent filter and a capability grant.',
    )


class Data17(BaseModel):
    factory: FactoryRef
    cwd: str = Field(..., description='Working directory for the spawned process.')
    cmd: list[str] = Field(..., description='The argv to execute.')
    resume: SessionId | None = Field(
        ...,
        description='Resume an existing session rather than starting fresh. Null starts a new one.',
    )
    origin: SpawnOrigin
    name: str | None = Field(
        ...,
        description='An optional recognizable name for the agent, shown instead of the bare id. Null leaves it unnamed.',
    )
    env: dict[str, str] | None = Field(
        None,
        description="Environment variables for the agent's process, on top of the producer's own. Configuration, possibly sensitive: it travels only on this command, and a producer never re-emits a value from it in any event. Absent adds nothing.",
    )
    in_place: StrictBool | None = Field(
        None,
        description='Run the agent in `cwd` itself, for an agent that owns a persistent working copy, rather than in an isolated copy the producer makes for it. A producer may refuse it while another live agent runs in that directory. Absent means false.',
    )


class BusCommand3(BaseModel):
    kind: Literal['SpawnAgent']
    data: Data17 = Field(..., description='Spawn a new agent process.')


class Data18(BaseModel):
    agent: AgentRef
    bytes: list[conint(ge=0, le=255, strict=True)] = Field(
        ..., description='The raw bytes to write, as octets.'
    )


class BusCommand4(BaseModel):
    kind: Literal['SendInput']
    data: Data18 = Field(
        ...,
        description="Write raw bytes to an agent's terminal — the keystream path, for interactive typing and menu navigation.",
    )


class Data19(BaseModel):
    agent: AgentRef
    text: str = Field(
        ..., description='The line to type and submit, with no trailing newline.'
    )


class BusCommand5(BaseModel):
    kind: Literal['SubmitLine']
    data: Data19 = Field(
        ...,
        description="Type one line at the agent's prompt and submit it.\n\nThis is not expressible as `SendInput` with a trailing newline, which is why it is its own command rather than a convenience: a terminator inside a single text burst is absorbed into the prompt's draft instead of submitting it, so submitting requires the host to split the write. Raw keystreams stay on `SendInput`.",
    )


class Data20(BaseModel):
    agent: AgentRef


class BusCommand6(BaseModel):
    kind: Literal['Focus']
    data: Data20 = Field(..., description="Switch the client's focused agent.")


class Data21(BaseModel):
    agent: AgentRef
    cols: conint(ge=0, le=65535, strict=True)
    rows: conint(ge=0, le=65535, strict=True)


class BusCommand7(BaseModel):
    kind: Literal['Resize']
    data: Data21 = Field(
        ...,
        description="Declare this connection's viewport for an agent. A declaration, not a command: the agent's terminal takes the smallest viewport declared across live connections, per dimension, or the producer's default when none is. A declaration lives while the agent is in the declaring connection's view subscription; it lapses on hang-up, on a `Subscribe` that drops the agent, or on one without `caps.view`. Wire shape unchanged since 0.1.0; only its arbitration changed.",
    )


class Data22(BaseModel):
    gate_id: GateId
    resolution: GateResolution


class BusCommand8(BaseModel):
    kind: Literal['GateAnswer']
    data: Data22 = Field(
        ...,
        description='Resolve an open gate. The one command that answers a permission prompt, a question, a memory promotion or a workflow gate — by id, in any of the three resolution modes.',
    )


class Data24(BaseModel):
    agent: AgentRef


class BusCommand11(BaseModel):
    kind: Literal['RequestFull']
    data: Data24 = Field(
        ...,
        description="Reship the agent's current screen to THIS connection as one full `Grid` frame, answered on the asking connection's stream in order with the deltas that follow.",
    )


class Data25(BaseModel):
    agent: AgentRef
    focused: StrictBool


class BusCommand12(BaseModel):
    kind: Literal['ViewerFocus']
    data: Data25 = Field(
        ...,
        description="Declare whether this connection's viewer has the agent focused. Aggregated like `Resize`: the agent counts as focused while any live viewer says so, and the producer reports a change to the application only if it enabled focus reporting.",
    )


class Data26(BaseModel):
    agent: AgentRef


class BusCommand13(BaseModel):
    kind: Literal['Quit']
    data: Data26 = Field(
        ...,
        description="Terminate the agent: the producer forgets its recovery record, then kills it, so it is never resumed. The only way to end an agent; closing or dropping a connection only detaches. Guarding against an accidental quit is the client's job.",
    )


class Data27(BaseModel):
    agent: AgentRef
    amount: dict[str, Any] | str = Field(
        ...,
        description='A `gridwire::ScrollAmount`, opaque to this schema: decode it with the `gridwire` crate\'s own `ScrollAmount` type. Its serde shape is gridwire\'s, verbatim; the envelope carries it without re-describing it, so the two cannot drift apart. A unit variant serializes as a bare string (`"PageUp"`), the others as a one-key object (`{"Lines": -3}`).',
    )


class BusCommand14(BaseModel):
    kind: Literal['Scroll']
    data: Data27 = Field(
        ...,
        description="Scroll the agent's shared display through its history; every viewer sees it. A no-op while the application is on the alternate screen. Accepted only from a connection viewing the agent.",
    )


class Data28(BaseModel):
    agent: AgentRef
    dir: conint(ge=-128, le=127, strict=True)


class BusCommand15(BaseModel):
    kind: Literal['JumpMark']
    data: Data28 = Field(
        ...,
        description="Put the agent's previous (negative) or next (positive) shell-integration mark at the top of its shared display. Accepted only from a connection viewing the agent.",
    )


class Data29(BaseModel):
    agent: AgentRef
    pattern: str
    forward: StrictBool


class BusCommand16(BaseModel):
    kind: Literal['Search']
    data: Data29 = Field(
        ...,
        description="Search the agent's history and screen for a regex and bring the match into view. The answer is a `SearchResult` event to every viewer; a client applies only a result it is awaiting. Accepted only from a connection viewing the agent.",
    )


class Target1(BaseModel):
    kind: Literal['One']
    id: AgentRef


class Target2(BaseModel):
    kind: Literal['Group']
    id: GroupRef


class Target3(BaseModel):
    kind: Literal['Factory']
    id: FactoryRef


class Target(RootModel[Target1 | Target2 | Target3 | Target4]):
    root: Target1 | Target2 | Target3 | Target4 = Field(
        ...,
        description='Where a command or message is delivered. Only `One` is implemented today; the rest are reserved so multicast lands without a wire change.',
        title='Target',
    )


class MailDraft(BaseModel):
    to: Target
    subject: str
    body: str


class Data(BaseModel):
    factory: FactoryRef
    role: AgentRole
    origin: SpawnOrigin
    name: str | None = Field(
        ...,
        description="The agent's recognizable name, if one was assigned at spawn. Echoed here so a client can label the agent without a second query. Null when unnamed, in which case clients display the id.",
    )


class EventKind1(BaseModel):
    kind: Literal['AgentAppeared']
    data: Data = Field(..., description='An agent process started.')


class EventKind2(BaseModel):
    kind: Literal['AgentStatus']
    data: AgentStatus


class EventKind6(BaseModel):
    kind: Literal['GateRequested']
    data: Gate


class Data4(BaseModel):
    to: Target
    from_: AgentRef = Field(..., alias='from')
    mail_id: MailId
    subject: str


class EventKind8(BaseModel):
    kind: Literal['MailArrived']
    data: Data4 = Field(
        ...,
        description='A mail message arrived — a hint to re-query the durable store, never the message itself. Durable things live in their own store; bus notifications about them are doorbells.',
    )


class ScreenSnapshot(BaseModel):
    cols: conint(ge=0, le=65535, strict=True)
    rows: conint(ge=0, le=65535, strict=True)
    cells: list[Cell]


class Data23(BaseModel):
    target: Target
    text: str


class BusCommand9(BaseModel):
    kind: Literal['Nudge']
    data: Data23 = Field(
        ...,
        description='Send a lightweight nudge. Deliberately not durable — a nudge that must survive the recipient going away is mail.',
    )


class BusCommand10(BaseModel):
    kind: Literal['MailSend']
    data: MailDraft


class BusCommand(
    RootModel[
        BusCommand1
        | BusCommand2
        | BusCommand3
        | BusCommand4
        | BusCommand5
        | BusCommand6
        | BusCommand7
        | BusCommand8
        | BusCommand9
        | BusCommand10
        | BusCommand11
        | BusCommand12
        | BusCommand13
        | BusCommand14
        | BusCommand15
        | BusCommand16
    ]
):
    root: (
        BusCommand1
        | BusCommand2
        | BusCommand3
        | BusCommand4
        | BusCommand5
        | BusCommand6
        | BusCommand7
        | BusCommand8
        | BusCommand9
        | BusCommand10
        | BusCommand11
        | BusCommand12
        | BusCommand13
        | BusCommand14
        | BusCommand15
        | BusCommand16
    ) = Field(
        ..., description='A command sent from a client to the bus.', title='BusCommand'
    )


class Body2(BaseModel):
    direction: Literal['Command']
    payload: BusCommand


class AgentView1(BaseModel):
    kind: Literal['Terminal']
    data: ScreenSnapshot


class AgentView(RootModel[AgentView1 | AgentView2 | AgentView3 | AgentView4]):
    root: AgentView1 | AgentView2 | AgentView3 | AgentView4 = Field(
        ...,
        description='The optional view tier, delivered only to clients that opt into it. This is the single exception to the rule that payloads carry refs and never content: the live terminal is the one thing an observer cannot reconstruct from ids.',
        title='AgentView',
    )


class EventKind3(BaseModel):
    kind: Literal['AgentView']
    data: AgentView


class EventKind(
    RootModel[
        EventKind1
        | EventKind2
        | EventKind3
        | EventKind4
        | EventKind5
        | EventKind6
        | EventKind7
        | EventKind8
        | EventKind9
        | EventKind10
        | EventKind11
        | EventKind12
        | EventKind13
        | EventKind14
        | EventKind15
        | EventKind16
        | EventKind17
        | EventKind18
        | EventKind19
    ]
):
    root: (
        EventKind1
        | EventKind2
        | EventKind3
        | EventKind4
        | EventKind5
        | EventKind6
        | EventKind7
        | EventKind8
        | EventKind9
        | EventKind10
        | EventKind11
        | EventKind12
        | EventKind13
        | EventKind14
        | EventKind15
        | EventKind16
        | EventKind17
        | EventKind18
        | EventKind19
    ) = Field(
        ...,
        description='The event payload. Deliberately a small, coarse set of per-plane verbs: fine-grained variety rides in plane-owned open-vocabulary string fields rather than in new kinds, which is what keeps this enumeration from sprawling.\n\nAdding a kind is an additive, minor change; a consumer that meets an unknown kind is meeting a newer peer, and should say so rather than guess. Note that a plane owning a vocabulary field means the bus transports its values without interpreting them — `verdict`, `outcome`, `deviation_kind`, `proposed_scope` and `source_trust` are all strings for that reason, not because their values are arbitrary.',
        title='EventKind',
    )


class BusEvent(BaseModel):
    id: EventId
    subject: SubjectRef
    attention: Attention
    kind: EventKind
    trace: TraceContext | None = Field(
        None,
        description='Cross-plane trace context. Absent means untraced, and an untraced event is byte-identical to one from before tracing existed — which is why this property is omitted rather than written as null. Producers propagate the context they were given, or mint one only at a true origin.',
    )


class Body1(BaseModel):
    direction: Literal['Event']
    payload: BusEvent


class Body(RootModel[Body1 | Body2]):
    root: Body1 | Body2 = Field(
        ...,
        description='The payload, discriminated by direction of travel. `Event` is bus to client; `Command` is client to bus.',
        title='Body',
    )


class Envelope(BaseModel):
    seq: conint(ge=0, le=18446744073709551615, strict=True) = Field(
        ...,
        description='Monotonic sequence number, per connection. Ordering and resync key: delivery is best-effort, so a client that sees a gap asks for a snapshot rather than assuming loss.',
    )
    at: conint(ge=0, le=18446744073709551615, strict=True) = Field(
        ...,
        description="Unix epoch milliseconds when the envelope was created. Stamped by the bus, never by the producer — a producer's own timestamp, where one exists, rides inside the payload as provenance (see `CurationProposed.ts`).",
    )
    body: Body
